### ISSUE TITLE
Falta un README que explique cómo añadir fuentes...

### ISSUE THREAD

**Issue by jorgesumle** [python-spain/planet.es.python.org#1]
Quisiera añadir la fuente de mi sitio web: https://www.freakspot.net/feeds/python.atom.xml

Pero no sé cuáles son los requisitos ni cómo hacerlo.

**Comment by astrojuanlu** [comment]
Esto quedó por definir y estaría bien rescatarlo. ¿Nos ayudas? :) Hago ping a @oscarmlage por si aún está interesado en retomar el tema.

**Comment by oscarmlage** [comment]
El 7/5/17 a las 19:03, Juan Luis Cano Rodríguez escribió:
> Esto quedó por definir y estaría bien rescatarlo. ¿Nos ayudas? :) Hago
> ping a @oscarmlage <https://github.com/oscarmlage> por si aún está
> interesado en retomar el tema.

Pong!. Creo que atm no hay ningún método ni ninguna información sobre
cómo agregar fuentes. Tendría que ponerme a ello... pasa que el tiempo
es un bien demasiado escaso últimamente. ¿Sugerencias?

-- 
Óscar M. Lage
http://oscarmlage.com

**Comment by yamila-moreno** [comment]
@Juanlu001 podría ser un mail a la lista de socios a ver si alguien se anima y recoge el guante desde aquí
